pipeline {
  agent any
  stages {
    stage('Clone Repo') {
      steps {
       // git 'https://github.com/Ajithkumar377/monitor.git'
        git branch: 'main', url: 'https://github.com/Ajithkumar377/monitor.git'

      }
    }
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t flask-app ./app'
      }
    }
    stage('Push to Docker Hub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
          sh '''
            docker login -u $USER -p $PASS
            docker tag flask-app ajithkumar377/flask-app
            docker push yourdockerhub/flask-app
          '''
        }
      }
    }
    stage('Deploy to K8s') {
      steps {
        sh '''
          kubectl apply -f ./k8s/deployment.yaml
          kubectl apply -f ./k8s/service.yaml
        '''
      }
    }
  }
}

